### PR TITLE
V 1.77

### PR DESCRIPTION
**Pull request by c-westhoven**
Small changes to make app MacOSVentura stable

### CODE REVIEW

**Comment by c-westhoven** [comment]
[histoCAT_1.77_manual.pdf](https://github.com/BodenmillerGroup/histoCAT/files/10531191/histoCAT_1.77_manual.pdf)
Also an updated version of the manual

**Comment by DenisSch** [comment]
@nilseling I think this is a great idea! How should we proceed?

**Comment by DenisSch** [comment]
This PR adresses #73

**Comment by nilseling** [comment]
Hi @DenisSch,

I think we should do three things:

1. could you let me know where to transfer the repository to? I will then perform the transfer and fork the repo back into `BodenmillerGroup`. Could also be that you need to do the transfer and I fork it back.
2. could you please open a PR on the fork that adds a transfer/deprecation note?
3. test if `histoCAT` is installable from the fork and the new location.

Let me know if that sounds alright to you.

**Comment by DenisSch** [comment]
@nilseling 
Let's do it :) 
Can you transfer it to: https://github.com/SchapiroLabor

**Pull request merged**
